app = "nicegui-minimal"  # change this to a unique name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true     # wake up on first request
  auto_stop_machines = "stop"    # allow machines to shut down
  min_machines_running = 0       # nothing runs when idle

  [http_service.concurrency]
    type = "requests"
    soft_limit = 10
    hard_limit = 15

