app = "your-unique-app-name"  # change this to a unique name
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 10
    hard_limit = 15
